apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: op
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: op
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50