apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: add
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: add
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50