apiVersion: v1
kind: Service
metadata:
  labels:
    app: add
  name: add
spec:
  ports:
    - name: 81-8080
      port: 81
      protocol: TCP
      targetPort: 8080
  selector:
    app: add
  type: LoadBalancer
status:
  loadBalancer: {}
