apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: calculator
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: calculator
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
