apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: calculator
  name: calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
        - image: localhost:5000/library/calculator:latest
          imagePullPolicy: Always
          name: calculator-container
          readinessProbe:
            initialDelaySeconds: 5
            httpGet:
              port: 8080
              path: /actuator/health/readiness
          livenessProbe:
            initialDelaySeconds: 5
            httpGet:
              port: 8080
              path: /actuator/health/liveness
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "0.5"

