apiVersion: v1
kind: Service
metadata:
  labels:
    app: calculator
  name: calculator
spec:
  ports:
    - name: 80-8080
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: calculator
  type: LoadBalancer
status:
  loadBalancer: {}
